---
apiVersion: v1
kind: Namespace
metadata:
  name: east
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: east
  labels:
    app: backend
  annotations:
    skupper.io/proxy: tcp
spec:
  selector:
    matchLabels:
      app: backend
  replicas: 3
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: quay.io/skupper/hello-world-backend
          ports:
            - containerPort: 8080
